### ISSUE TITLE
The mess with patches ....

### ISSUE THREAD

**Issue by kollokollo** [haegar/xv#1]
May I suggest to restructure the while repository and reconstruct the individual patches, such that each patch gets its own commit (preferrably in historic / cronological order)? I am lost in the ordering of all thouse patches and cannot merge my fork/branch with yours and Fabians...

**Comment by haegar** [comment]
Sorry, I won't be able to do that - I don't even know which base patches are included, I just took Fabians repository from git://anonscm.debian.org/collab-maint/xv.git and modified the debian packaging to make it work on a current system.

The patches I've put on top are available inside the debian/patches subdirectory, with the series file describing the order.

**Comment by kollokollo** [comment]
OK, I try to apply at least individual jumbo patches and male a good timeline in my repository, however, I could not exactly reproduce your state of the code and also I does not yet compile without errors on Ubuntu 17.4 64bit. Just for your information.

**Comment by haegar** [comment]
Builds a working package just fine for me in current Debian Unstable, both i386 and amd64, using "debuild".

Note that non-packaging build is not supported, as that would not apply the additional patches from debian/patches subdir, which are NOT applied in the git repository but only get applied at build-time.

**Comment by kollokollo** [comment]
I see. Well, I try to make a version which just compiles out of the sources. Would be some work,I guess...

**Comment by haegar** [comment]
Not really - you just need to apply the debian/patches files in the order they are listed in debian/patches/series and commit each result.

**Comment by kollokollo** [comment]
Yep, you were right, I made it. Now i compiles. I think now the debian/patches/series needs to be modified, so that also a debian package can be made. but I am not the expert in debian packages.

**Comment by haegar** [comment]
That is also easy, just delete the applied single patch files and remove their names from the debian/patches/series file - an empty file (or even a missing debian/patches directory) mean no patches to apply at build-time.

**Comment by kollokollo** [comment]
Ok, done. Many thanks for guidance. It compiles now well on 64 bit Ubuntu 17.4 but there is still one error on comiling on 32bit Ubuntu 17.4. Strange but also there it could be fixed.
